; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.30"

; Modules
projects[ctools][version] = "1.4"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[og][version] = "2.7"

